<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
    <div>
        <nav class="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-slate-400" aria-label="Breadcrumb"><a href="<?php echo site_url('sales'); ?>" class="hover:text-brand-700">Sales invoices</a><span aria-hidden="true">/</span><span class="text-slate-600"><?php echo html_escape($sale->invoice_number); ?></span></nav>
        <h1 class="text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl"><?php echo html_escape($sale->invoice_number); ?></h1>
        <p class="mt-2 text-sm text-slate-600">Finalized <?php echo html_escape(date('F j, Y \a\t H:i', strtotime($sale->created_at))); ?></p>
    </div>
    <div class="flex flex-wrap gap-2"><a href="<?php echo site_url('sales'); ?>" class="inline-flex min-h-11 items-center rounded-xl border border-slate-300 bg-white px-4 text-sm font-semibold text-slate-700 hover:border-brand-300 hover:text-brand-700">Back to invoices</a><a href="<?php echo site_url('sales/create'); ?>" class="inline-flex min-h-11 items-center rounded-xl bg-brand-600 px-4 text-sm font-semibold text-white hover:bg-brand-700">New invoice</a></div>
</div>

<section class="mb-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4" aria-label="Invoice information">
    <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Customer</p><p class="mt-2 font-bold text-slate-900"><?php echo html_escape($sale->customer_name); ?></p><?php if ($sale->customer_email): ?><p class="mt-1 text-xs text-slate-500"><?php echo html_escape($sale->customer_email); ?></p><?php endif; ?><?php if ($sale->customer_phone): ?><p class="mt-1 text-xs text-slate-500"><?php echo html_escape($sale->customer_phone); ?></p><?php endif; ?></article>
    <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Warehouse</p><p class="mt-2 font-bold text-slate-900"><?php echo html_escape($sale->warehouse_name); ?></p><p class="mt-1 font-mono text-xs text-slate-500"><?php echo html_escape($sale->warehouse_code); ?></p></article>
    <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Issued by</p><p class="mt-2 font-bold text-slate-900"><?php echo html_escape($sale->user_name ?: 'System / legacy'); ?></p><?php if ($sale->user_email): ?><p class="mt-1 text-xs text-slate-500"><?php echo html_escape($sale->user_email); ?></p><?php endif; ?></article>
    <article class="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 shadow-sm"><p class="text-xs font-bold uppercase tracking-wider text-emerald-700">Final total</p><p class="mt-2 text-2xl font-bold tabular-nums text-emerald-950">$<?php echo html_escape(number_format((float) $sale->total, 2)); ?></p><p class="mt-1 text-xs text-emerald-700">Saved and stock deducted</p></article>
</section>

<div class="grid gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(300px,1fr)]">
    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div class="border-b border-slate-200 px-5 py-4"><h2 class="font-bold text-slate-900">Invoice lines</h2><p class="mt-1 text-xs text-slate-500">Prices shown are the historical values saved with this invoice.</p></div>
        <div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-left text-sm"><thead class="bg-slate-50 text-xs font-semibold uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-3">Product</th><th class="px-5 py-3 text-right">Quantity</th><th class="px-5 py-3 text-right">Unit price</th><th class="px-5 py-3 text-right">Subtotal</th></tr></thead><tbody class="divide-y divide-slate-100">
            <?php foreach ($items as $item): ?><tr><td class="px-5 py-4"><p class="font-semibold text-slate-900"><?php echo html_escape($item->product_name); ?></p><p class="mt-1 font-mono text-xs text-slate-400"><?php echo html_escape($item->product_code); ?></p></td><td class="whitespace-nowrap px-5 py-4 text-right font-semibold tabular-nums text-slate-800"><?php echo html_escape(number_format((int) $item->quantity)); ?></td><td class="whitespace-nowrap px-5 py-4 text-right tabular-nums text-slate-600">$<?php echo html_escape(number_format((float) $item->unit_price, 2)); ?></td><td class="whitespace-nowrap px-5 py-4 text-right font-bold tabular-nums text-slate-950">$<?php echo html_escape(number_format((float) $item->subtotal, 2)); ?></td></tr><?php endforeach; ?>
        </tbody></table></div>
    </section>
    <aside class="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 class="font-bold text-slate-900">Totals</h2><dl class="mt-5 space-y-4 text-sm"><div class="flex justify-between gap-4 text-slate-600"><dt>Subtotal</dt><dd class="font-semibold tabular-nums text-slate-900">$<?php echo html_escape(number_format((float) $sale->subtotal, 2)); ?></dd></div><div class="flex justify-between gap-4 text-slate-600"><dt>Discount (<?php echo html_escape(number_format((float) $sale->discount_percentage, 2)); ?>%)</dt><dd class="font-semibold tabular-nums text-slate-900">-$<?php echo html_escape(number_format((float) $sale->discount_amount, 2)); ?></dd></div><div class="flex justify-between gap-4 border-t border-slate-200 pt-4"><dt class="font-bold text-slate-900">Total</dt><dd class="text-xl font-bold tabular-nums text-slate-950">$<?php echo html_escape(number_format((float) $sale->total, 2)); ?></dd></div></dl><p class="mt-6 rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-500">Invoice prices and totals were validated server-side. This record is read-only.</p></aside>
</div>
